### ISSUE TITLE
Idea: add a password to enter a room

### ISSUE THREAD

**Issue by Quenty31** [darkwire/darkwire.io#109]
Just so anyone cannot enter and follow the conversation.
It would add a layer of protection, small but still.

**Comment by seripap** [comment]
Hi, you can lock the room to prevent others from joining by clicking the unlock button in the header. The Icon will changed to a locked state which will not allow anyone to join until it is unlocked again. This feature can only be used by the room owner.

<img width="300" alt="Screen Shot 2019-08-29 at 2 29 25 PM" src="https://user-images.githubusercontent.com/683200/63966509-73853f80-ca69-11e9-9bd0-19b440713169.png">

**Comment by Quenty31** [comment]
Yes yes but imagine:
you are waiting your friends, and waiting to lock the room, but someone enters :O
Can you kick them?
