### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jrmi** [darkwire/darkwire.io#131]
Add a CI like:
- [Travis](https://travis-ci.org/)
- [CircleCI](https://circleci.com/)
- [Github Action](https://github.com/features/actions)

Which one do you prefer ?

**Comment by alanfriedman** [comment]
We already have CircleCI configured so I would vote we stick with that 👍

**Comment by jrmi** [comment]
Oh right ! I didn't see it ;-)
