### ISSUE TITLE
Store configuration is not loaded

### ISSUE THREAD

**Issue by jrmi** [darkwire/darkwire.io#142]
Due to the way import works, dotenv file is loaded after `store` file. The store initialisation should be lazy.

**Comment by alanfriedman** [comment]
Hmm I haven't tested this locally but that shouldn't be the case. How can I reproduce this?

**Comment by jrmi** [comment]
Try to use the `memory` backend. Since the store initialisation is in another file, it's broken and it always take the default values as `process.env` is not populated with `.env` file.

**Comment by jrmi** [comment]
in my understanding, the module imports are done and then the code is executed. The problem with the `require(dotenv).config` line is that the `.config()` is executed after the all other import are done so the `store/index.js` is loaded before the `process.env` population, which then initialized without the variables in the `.env` file.
