### ISSUE TITLE
unnecessary updown page option coming in welcome prompt

### ISSUE THREAD

**Issue by navnit0707** [darkwire/darkwire.io#161]
when i visit site a welcome popup comes with an unnecessary up and down option on close button as shown in the screenshot. i want to fix It
![Screenshot (415)](https://user-images.githubusercontent.com/40719341/88892262-2190ff00-d262-11ea-9d3c-9d96b5961419.png)

tell me if it will be helpful or not for you . if helpful i want to fix it

**Comment by jrmi** [comment]
That's a good idea.This problem seems to be limited to certain browsers. What is your browser? Feel free to contribute.

**Comment by navnit0707** [comment]
yeah I tried to understand why this problem occurs, like some times it comes some time not I am using chrome ...unable to understand proper reason have you any idea why sometimes it appears and sometimes its works as expected

**Comment by jrmi** [comment]
I have no idea. I fail to reliably reproduce this bug.

**Comment by navnit0707** [comment]
yeah! i also check whole code related to this ...but unable to find any sufficient reason why this was happening . I have also no clue . So i am closing it.
