### ISSUE TITLE
Suggestion: security is based on a Diffie–Hellman key exchange method, maybe mention it in readme.md ?

### ISSUE THREAD

**Issue by pavlobu** [darkwire/darkwire.io#169]
Hello 

Thanks for sharing this awesome project!

I was going through code and readme, and I can say that this encryption method is based on [Diffie–Hellman key exchange](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange) 
and there is a good video explaining what it is: [End to End Encryption (E2EE) - Computerphile](https://www.youtube.com/watch?v=jkV1KEJGKRA)

Maybe you can mention it in readme.md that it is a Diffie-Hellman based solution and include a link to [wikipedia page](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange) ?

It would definitely help people who are new to security and end-to-end encryption to understand this project more if they 
find info on what Diffie–Hellman is.

Cheers,
Paul

**Comment by jrmi** [comment]
Hi,

I'm not an expert myself but I don't think it's a Diffie–Hellman key exchange here, but something based on top of RSA key pairs.

**Comment by pavlobu** [comment]
Ok got it.
I understand that it is not a pure Diffie-Hellman key exchange here. But it really looks like Diffie-Hellman when we exchange public keys with others at first glance.
