### ISSUE TITLE
Promote | partnership with Rovel Stars!

### ISSUE THREAD

**Issue by sayantan300** [darkwire/darkwire.io#186]
Hey devs, I'm the owner of Rovel Stars, a team on Discord, which has some awesome projects like:-
- [URL shortener](https://url.rovelstars.ga)
- [Rovel Paste](https://paste.rovelstars.ga)
- [Rovel Bot List](https://bots.rovelstars.ga)
- [Rovel Blog](https://blog.rovelstars.ga)
I want your services (chat room) integration with my projects (using iframe of course).
So, do you all accept my invitation to partner?

**Comment by seripap** [comment]
Hi feel free to link out to Darkwire for your specific purpose, but we are not looking for partnerships at the moment.
