### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by alanfriedman** [darkwire/darkwire.io#61]
Hi Darkwire users,

We are planning to internationalize all content to support our non-English speaking users. Please vote below for the language you'd most like to see translated first, or list a different language in the comments. We'll use this to help prioritize translation.

[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/French)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/French/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Spanish)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Spanish/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Chinese)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Chinese/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/German)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/German/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Arabic)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Arabic/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Hindi)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Hindi/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Russian)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Russian/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Japanese)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Japanese/vote)
[![](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Korean)](https://api.gh-polls.com/poll/01C1D1HXG5VGD0P7CF6HQK69T3/Korean/vote)

**Comment by Invictaz** [comment]
Where is Dutch?

**Comment by alanfriedman** [comment]
@Invictaz I'll take that as a +1 for Dutch

**Comment by tux-tn** [comment]
I can help for french translation

Le 21 déc. 2017 00:05, à 00:05, Alan Friedman <notifications@github.com> a écrit:

**Comment by VonKavalier** [comment]
I can help for a french translation too :)

**Comment by alanfriedman** [comment]
Thanks everyone for the feedback, and @tux-tn and @VonKavalier we'll likely take you up on that offer.

As for the implementation there are a few options:

- URL path - `darkwire.io/fr/room-id`
- Subdomain - `fr.darkwire.io/room-id`
- Settings stored in cookie/local storage - `darkwire.io/room-id`

Any preferences?

**Comment by VonKavalier** [comment]
Nice, I'll be ready when you are 🙂
And for the implementation I'd go for a cookie/local storage, because I see it easier to share a room with a non French person for example.

**Comment by alanfriedman** [comment]
@tux-tn @VonKavalier We could use your help translating Darkwire to French! You can find the translation file [here](https://github.com/darkwire/darkwire.io/blob/master/client/src/i18n/fr.json). Would love to merge a PR!

**Comment by VonKavalier** [comment]
With pleasure ! I'll try to work on it today :)

**Comment by VonKavalier** [comment]
Here is the PR : https://github.com/darkwire/darkwire.io/pull/87

**Comment by alanfriedman** [comment]
Thanks @VonKavalier! Enabling French now: #88

**Comment by alanfriedman** [comment]
@Invictaz Would you be able to help with the Dutch translations?

**Comment by Invictaz** [comment]
@alanfriedman Sure here it is. Not sure if I translated every sentence.

[nl.txt](https://github.com/darkwire/darkwire.io/files/3318384/nl.txt)

**Comment by Invictaz** [comment]
@alanfriedman Did you receive it?

**Comment by alanfriedman** [comment]
@Invictaz Sorry for the delayed response. I was able to see the HTML but would you mind moving it to JSON format. This [recent PR](https://github.com/darkwire/darkwire.io/pull/95) is a great example of what we're looking for. Thank you for you time and contributions!

**Comment by Invictaz** [comment]
@alanfriedman I forgot about this. Sorry. Shall I open a new issue on the Dutch translation. Or will you reopen this.

**Comment by alanfriedman** [comment]
@Invictaz No problem. Feel free to open a new issue for Dutch. This was just a poll to get a feel for our users' language preferences.
